In [ ]:
#W11 AdventureWorks

In [25]:
%run connessioneSQL.py

In [26]:
query = "SELECT * FROM dimemployee"
de=pd.read_sql(query, db_engine)
de

,EmployeeKey,ParentEmployeeKey,EmployeeNationalIDAlternateKey,ParentEmployeeNationalIDAlternateKey,FirstName,LastName,MiddleName,NameStyle,Title,HireDate,...,Gender,PayFrequency,BaseRate,VacationHours,SickLeaveHours,CurrentFlag,SalesPersonFlag,DepartmentName,EmployeePhoto,Position
0,1,18.0,14417807,446466105.0,Guy,Gilbert,R,0,Production Technician - WC60,2006-01-28,...,M,1,12.4500,21,30,1,0,Production,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
1,2,7.0,253022876,24756624.0,Kevin,Brown,F,0,Marketing Assistant,2006-08-26,...,M,2,13.4615,42,41,1,0,Marketing,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
2,3,14.0,509647174,245797967.0,Roberto,Tamburello,None,0,Engineering Manager,2007-06-11,...,M,2,43.2692,2,21,1,0,Engineering,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
3,4,3.0,112457891,509647174.0,Rob,Walters,None,0,Senior Tool Designer,2007-07-05,...,M,2,29.8462,48,80,1,0,Tool Design,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
4,5,3.0,112457891,509647174.0,Rob,Walters,None,0,Senior Tool Designer,2007-07-05,...,M,2,29.8462,48,80,1,0,Tool Design,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,292,290.0,134219713,982310417.0,Ranjit,Varkey Chudukatil,R,0,Sales Representative,2011-12-29,...,M,2,23.0769,34,37,1,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
292,293,272.0,90836195,502097814.0,Tete,Mensa-Annan,A,0,Sales Representative,2012-04-30,...,M,2,23.0769,39,39,1,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
293,294,277.0,481044938,112432117.0,Syed,Abbas,E,0,Pacific Sales Manager,2012-10-12,...,M,2,48.1010,20,30,1,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Manager
294,295,290.0,954276278,982310417.0,Rachel,Valdez,B,0,Sales Representative,2012-12-28,...,F,2,23.0769,35,37,1,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
295,296,294.0,758596752,481044938.0,Lynn,Tsoflias,N,0,Sales Representative,2012-12-28,...,F,2,23.0769,36,38,1,1,Sales,b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\...,Sales Representative

In [27]:
query="SELECT * FROM dimemployeesalesterritory"
des=pd.read_sql(query, db_engine)
des

    EmployeeKey  SalesTerritoryKey
0           272                  1
1           277                  1
2           286                  1
3           289                  1
4           293                  1
5           272                  2
6           277                  2
7           281                  2
8           272                  3
9           277                  3
10          281                  3
11          282                  3
12          283                  3
13          272                  4
14          277                  4
15          282                  4
16          286                  4
17          287                  4
18          272                  5
19          277                  5
20          281                  5
21          285                  5
22          272                  6
23          277                  6
24          284                  6
25          288                  6
26          277                  7
27          290                  7
28          291                  7
29          292                  7
30          277                  8
31          290                  8
32          295                  8
33          277                  9
34          294                  9
35          296                  9
36          277                 10
37          290                 10
38          291                 10

In [28]:
# Effettuiamo un join tra i due DataFrame usando le colonne EmployeeKey
de=de.set_index("EmployeeKey")
des=des.set_index("EmployeeKey")
print("shape di de", de.shape)
print("shape di des", des.shape)

shape di de (296, 27)
shape di des (39, 1)

In [14]:
de_join_des=de.join(des)
de_join_des=de_join_des.reset_index()
de_join_des[["EmployeeKey","SalesTerritoryKey"]]

     EmployeeKey  SalesTerritoryKey
0              1                NaN
1              2                NaN
2              3                NaN
3              4                NaN
4              5                NaN
..           ...                ...
312          292                7.0
313          293                1.0
314          294                9.0
315          295                8.0
316          296                9.0

[317 rows x 2 columns]

In [29]:
#Controlliamo la dimensione del DataFrame risultante: è quella attesa?
de_join_des.shape
#317=296 da emp con 21 dup da des =317 della join

(317, 29)

In [41]:
#Importiamo ora la tabella dimsalesterritory ed effettuiamo un join tra questa e il DataFrame risultante della join precedente, usando le colonne SalesTerritoryKey
de_join_des=de_join_des.set_index("SalesTerritoryKey")
de_join_des

,EmployeeKey,ParentEmployeeKey,EmployeeNationalIDAlternateKey,ParentEmployeeNationalIDAlternateKey,FirstName,LastName,MiddleName,NameStyle,Title,HireDate,...,Gender,PayFrequency,BaseRate,VacationHours,SickLeaveHours,CurrentFlag,SalesPersonFlag,DepartmentName,EmployeePhoto,Position
SalesTerritoryKey,,,,,,,,,,,,,,,,,,,,,
NaN,1,18.0,14417807,446466105.0,Guy,Gilbert,R,0,Production Technician - WC60,2006-01-28,...,M,1,12.4500,21,30,1,0,Production,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
NaN,2,7.0,253022876,24756624.0,Kevin,Brown,F,0,Marketing Assistant,2006-08-26,...,M,2,13.4615,42,41,1,0,Marketing,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
NaN,3,14.0,509647174,245797967.0,Roberto,Tamburello,None,0,Engineering Manager,2007-06-11,...,M,2,43.2692,2,21,1,0,Engineering,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
NaN,4,3.0,112457891,509647174.0,Rob,Walters,None,0,Senior Tool Designer,2007-07-05,...,M,2,29.8462,48,80,1,0,Tool Design,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
NaN,5,3.0,112457891,509647174.0,Rob,Walters,None,0,Senior Tool Designer,2007-07-05,...,M,2,29.8462,48,80,1,0,Tool Design,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7.0,292,290.0,134219713,982310417.0,Ranjit,Varkey Chudukatil,R,0,Sales Representative,2011-12-29,...,M,2,23.0769,34,37,1,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
1.0,293,272.0,90836195,502097814.0,Tete,Mensa-Annan,A,0,Sales Representative,2012-04-30,...,M,2,23.0769,39,39,1,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
9.0,294,277.0,481044938,112432117.0,Syed,Abbas,E,0,Pacific Sales Manager,2012-10-12,...,M,2,48.1010,20,30,1,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Manager
8.0,295,290.0,954276278,982310417.0,Rachel,Valdez,B,0,Sales Representative,2012-12-28,...,F,2,23.0769,35,37,1,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
9.0,296,294.0,758596752,481044938.0,Lynn,Tsoflias,N,0,Sales Representative,2012-12-28,...,F,2,23.0769,36,38,1,1,Sales,b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\...,Sales Representative

In [43]:
query="SELECT * FROM dimsalesterritory"
dst=pd.read_sql(query, db_engine)
dst

,SalesTerritoryKey,SalesTerritoryAlternateKey,SalesTerritoryRegion,SalesTerritoryCountry,SalesTerritoryGroup,SalesTerritoryImage
0,1,1,Northwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
1,2,2,Northeast,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
2,3,3,Central,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
3,4,4,Southwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
4,5,5,Southeast,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
5,6,6,Canada,Canada,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
6,7,7,France,France,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
7,8,8,Germany,Germany,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
8,9,9,Australia,Australia,Pacific,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
9,10,10,United Kingdom,United Kingdom,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
10,11,0,Corporate HQ,Corporate HQ,Corporate HQ,None

In [44]:
dst=dst.set_index("SalesTerritoryKey")
dst

,SalesTerritoryAlternateKey,SalesTerritoryRegion,SalesTerritoryCountry,SalesTerritoryGroup,SalesTerritoryImage
SalesTerritoryKey,,,,,
1,1,Northwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
2,2,Northeast,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
3,3,Central,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
4,4,Southwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
5,5,Southeast,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
6,6,Canada,Canada,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
7,7,France,France,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
8,8,Germany,Germany,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
9,9,Australia,Australia,Pacific,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
10,10,United Kingdom,United Kingdom,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
11,0,Corporate HQ,Corporate HQ,Corporate HQ,None

In [46]:
#join
dst_join_des=dst.join(de_join_des)
dst_join_des

,SalesTerritoryAlternateKey,SalesTerritoryRegion,SalesTerritoryCountry,SalesTerritoryGroup,SalesTerritoryImage,EmployeeKey,ParentEmployeeKey,EmployeeNationalIDAlternateKey,ParentEmployeeNationalIDAlternateKey,FirstName,...,Gender,PayFrequency,BaseRate,VacationHours,SickLeaveHours,CurrentFlag,SalesPersonFlag,DepartmentName,EmployeePhoto,Position
SalesTerritoryKey,,,,,,,,,,,,,,,,,,,,,
1.0,1,Northwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,272.0,277.0,502097814.0,112432117.0,Stephen,...,M,2.0,48.1010,14.0,27.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Manager
1.0,1,Northwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,277.0,277.0,112432117.0,112432117.0,Brian,...,M,2.0,72.1154,10.0,25.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Director
1.0,1,Northwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,286.0,272.0,61161660.0,502097814.0,Pamela,...,F,2.0,23.0769,22.0,31.0,1.0,1.0,Sales,b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\...,Sales Representative
1.0,1,Northwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,289.0,272.0,987554265.0,502097814.0,David,...,M,2.0,23.0769,23.0,31.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
1.0,1,Northwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,293.0,272.0,90836195.0,502097814.0,Tete,...,M,2.0,23.0769,39.0,39.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
2.0,2,Northeast,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,272.0,277.0,502097814.0,112432117.0,Stephen,...,M,2.0,48.1010,14.0,27.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Manager
2.0,2,Northeast,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,277.0,277.0,112432117.0,112432117.0,Brian,...,M,2.0,72.1154,10.0,25.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Director
2.0,2,Northeast,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,281.0,272.0,841560125.0,502097814.0,Michael,...,M,2.0,23.0769,38.0,39.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
3.0,3,Central,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,272.0,277.0,502097814.0,112432117.0,Stephen,...,M,2.0,48.1010,14.0,27.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Manager
3.0,3,Central,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,277.0,277.0,112432117.0,112432117.0,Brian,...,M,2.0,72.1154,10.0,25.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Director
3.0,3,Central,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,281.0,272.0,841560125.0,502097814.0,Michael,...,M,2.0,23.0769,38.0,39.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
3.0,3,Central,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,282.0,272.0,191644724.0,502097814.0,Linda,...,F,2.0,23.0769,27.0,33.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
3.0,3,Central,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,283.0,272.0,615389812.0,502097814.0,Jillian,...,F,2.0,23.0769,24.0,32.0,1.0,1.0,Sales,b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\...,Sales Representative
4.0,4,Southwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,272.0,277.0,502097814.0,112432117.0,Stephen,...,M,2.0,48.1010,14.0,27.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Manager
4.0,4,Southwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,277.0,277.0,112432117.0,112432117.0,Brian,...,M,2.0,72.1154,10.0,25.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Director
4.0,4,Southwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,282.0,272.0,191644724.0,502097814.0,Linda,...,F,2.0,23.0769,27.0,33.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
4.0,4,Southwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,286.0,272.0,61161660.0,502097814.0,Pamela,...,F,2.0,23.0769,22.0,31.0,1.0,1.0,Sales,b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\...,Sales Representative
4.0,4,Southwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,287.0,272.0,139397894.0,502097814.0,Shu,...,M,2.0,23.0769,26.0,33.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
5.0,5,Southeast,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,272.0,277.0,502097814.0,112432117.0,Stephen,...,M,2.0,48.1010,14.0,27.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Manager
5.0,5,Southeast,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,277.0,277.0,112432117.0,112432117.0,Brian,...,M,2.0,72.1154,10.0,25.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Director
5.0,5,Southeast,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,281.0,272.0,841560125.0,502097814.0,Michael,...,M,2.0,23.0769,38.0,39.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
5.0,5,Southeast,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,285.0,272.0,716374314.0,502097814.0,Tsvi,...,M,2.0,23.0769,29.0,34.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
6.0,6,Canada,Canada,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,272.0,277.0,502097814.0,112432117.0,Stephen,...,M,2.0,48.1010,14.0,27.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Manager
6.0,6,Canada,Canada,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,277.0,277.0,112432117.0,112432117.0,Brian,...,M,2.0,72.1154,10.0,25.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Director
6.0,6,Canada,Canada,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,284.0,272.0,234474252.0,502097814.0,Garrett,...,M,2.0,23.0769,33.0,36.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
6.0,6,Canada,Canada,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,288.0,272.0,399771412.0,502097814.0,José,...,M,2.0,23.0769,31.0,35.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
7.0,7,France,France,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,277.0,277.0,112432117.0,112432117.0,Brian,...,M,2.0,72.1154,10.0,25.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Director
7.0,7,France,France,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,290.0,277.0,982310417.0,112432117.0,Amy,...,F,2.0,48.1010,21.0,30.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Manager
7.0,7,France,France,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,291.0,290.0,668991357.0,982310417.0,Jae,...,F,2.0,23.0769,37.0,38.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
7.0,7,France,France,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,292.0,290.0,134219713.0,982310417.0,Ranjit,...,M,2.0,23.0769,34.0,37.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
8.0,8,Germany,Germany,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,277.0,277.0,112432117.0,112432117.0,Brian,...,M,2.0,72.1154,10.0,25.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Director
8.0,8,Germany,Germany,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,290.0,277.0,982310417.0,112432117.0,Amy,...,F,2.0,48.1010,21.0,30.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Manager
8.0,8,Germany,Germany,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,295.0,290.0,954276278.0,982310417.0,Rachel,...,F,2.0,23.0769,35.0,37.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
9.0,9,Australia,Australia,Pacific,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,277.0,277.0,112432117.0,112432117.0,Brian,...,M,2.0,72.1154,10.0,25.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Director
9.0,9,Australia,Australia,Pacific,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,294.0,277.0,481044938.0,112432117.0,Syed,...,M,2.0,48.1010,20.0,30.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Manager
9.0,9,Australia,Australia,Pacific,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,296.0,294.0,758596752.0,481044938.0,Lynn,...,F,2.0,23.0769,36.0,38.0,1.0,1.0,Sales,b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\...,Sales Representative
10.0,10,United Kingdom,United Kingdom,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,277.0,277.0,112432117.0,112432117.0,Brian,...,M,2.0,72.1154,10.0,25.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Director
10.0,10,United Kingdom,United Kingdom,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,290.0,277.0,982310417.0,112432117.0,Amy,...,F,2.0,48.1010,21.0,30.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Manager
10.0,10,United Kingdom,United Kingdom,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,291.0,290.0,668991357.0,982310417.0,Jae,...,F,2.0,23.0769,37.0,38.0,1.0,1.0,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
11.0,0,Corporate HQ,Corporate HQ,Corporate HQ,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN